//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatFinalni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontakt()
        {
            this.MailAdresas = new HashSet<MailAdresa>();
            this.Telefons = new HashSet<Telefon>();
        }
    
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string RadnoMesto { get; set; }
        public int SkolaID { get; set; }
        public int KontaktID { get; set; }

        

        internal void NapraviTelefon(int count = 1)
        {
            for (int i = 0; i < count; i++)
            {
                Telefons.Add(new Telefon());
            }
        }

        internal void NapraviEmail(int count = 1)
        {
            for (int i = 0; i < count; i++)
            {
                MailAdresas.Add(new MailAdresa());
            }
        }
        public virtual Skola Skola { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailAdresa> MailAdresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefon> Telefons { get; set; }
    }
}
