//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatFinalni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAdresa
    {
        public string Adresa { get; set; }
        public string OznakaTipaMail { get; set; }
        public int KontaktID { get; set; }
    
        public virtual Kontakt Kontakt { get; set; }
    }
}
