//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatFinalni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skola
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skola()
        {
            this.Kontakts = new HashSet<Kontakt>();
        }
    
        public int SkolaID { get; set; }
        public string NazivSkole { get; set; }
        public string AdresaRegistracije { get; set; }
        public string Opstina { get; set; }
        public Nullable<int> PostanskiBroj { get; set; }
        public string MaticniBrojSkole { get; set; }
        public string PIB { get; set; }
        public string BrojRacunaSkole { get; set; }
        public string WebStranica { get; set; }
        public byte[] Fotografija { get; set; }
        public string Beleska { get; set; }
        public List<Kontakt> Kontakti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontakt> Kontakts { get; set; }
    }
}
